### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by JSONY18** [skarnet/execline#5]
I tried to build with the latest release and previous versions. It pops up different error issue. Could you provide a compatible version among skalibs && execline && s6? thanks
`src/libexecline/el_modif_and_spawn.c: In function 'el_modif_and_spawn':
src/libexecline/el_modif_and_spawn.c:24:3: error: implicit declaration of function 'env_mergen' [-Werror=implicit-function-declaration]
   if (!env_mergen(newenv, envlen + 2, (char const *const *)environ, envlen, value ? modifs : var, value ? modiflen : varlen + 1, 1)) return 0 ;
   ^
cc1: some warnings being treated as errors
make: *** [Makefile:135: src/libexecline/el_modif_and_spawn.lo] Error 1`

**Comment by skarnet** [comment]
execline version 2.7.0.0 builds with skalibs version 2.10.0.0 or later. Please make sure your skalibs version is up-to-date.
